### ISSUE TITLE
Finish Song CRUD

### ISSUE THREAD

**Issue by AK3030** [AK3030/MusicNimbus#14]

**Comment by niartenyaw** [comment]
Nice!

## Functionality

- [x] Can't upload a song correctly. There seems to be two spaces to upload songs as well. Might only want to handle one.

The other portions of this look great!

**Comment by AK3030** [comment]
Just fixed the styling of the upload form. Let me know if it's still not working. Keep in mind I don't have any loading indicators so you'll have to wait a little while with no feedback.
